# Generated by Django 4.2.15 on 2024-08-30 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.PositiveIntegerField(choices=[(1, 'Standard 1'), (2, 'Standard 2'), (3, 'Standard 3'), (4, 'Standard 4'), (5, 'Standard 5'), (6, 'Standard 6'), (7, 'Standard 7'), (8, 'Standard 8'), (9, 'Standard 9'), (10, 'Standard 10'), (11, 'Standard 11'), (12, 'Standard 12')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roll_no', models.PositiveIntegerField(blank=True, null=True)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.standard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
